/*========================= CHARACTER FUNCTION IN SAS =========================*/

/* TASK- SCAN(2 EXAMPLES)- EACH 30 EXAMPLE [WITHOUT,WITH DELIMATED],SUBSTR-30 [normal extract,or replacement] */

/* EXAMPLE1 */
DATA STUDENT_DATA;
NAME="Rahul Sharma";
LAST_NAME=SCAN(NAME,2);
RUN;

/* EXAMPLE2 */
DATA PATIENT_DATA;
PATIENT="Anita Kumari Singh";
MIDDLE_NAME=SCAN(PATIENT,2);
RUN;

/* EXAMPLE3 */
DATA COUNTRY_DATA;
LOCATION="New Delhi India";
COUNTRY=SCAN(LOCATION,3);
RUN;

/* EXAMPLE4 */
DATA DRUG_DATA;
DRUG="Paracetamol 500 Tablet";
STRENGTH=SCAN(DRUG,2);
RUN;

/* EXAMPLE5 */
DATA VISIT_DATA;
VISIT="Visit 02 Screening";
VISIT_NO=SCAN(VISIT,2);
RUN;

/* EXAMPLE6 */
DATA DOCTOR_DATA;
DOCTOR="Dr Amit Kumar";
FIRST_NAME=SCAN(DOCTOR,1);
RUN;

/* EXAMPLE7 */
DATA HOSPITAL_DATA;
HOSPITAL="Apollo Hospital Chennai";
CITY=SCAN(HOSPITAL,3);
RUN;

/* EXAMPLE8 */
DATA COURCE_DATA;
COURSE="Clinical SAS Programming";
COURCE_NAME=SCAN(COURSE,2);
RUN;

/* EXAMPLE9 */
DATA EMPLOYEE_DATA;
EMPLOYEE="Priya Verma Manager";
DESIGNATION=SCAN(EMPLOYEE,3);
RUN;

/* EXAMPLE10 */
DATA ADDRESS_DATA;
ADDRESS="Bangalore Karnataka India";
STATE=SCAN(ADDRESS,2);
RUN;

/* EXAMPLE11 */
DATA COURSE_DATA;
COURSE="Clinical SAS Programming";
COURSE_NAME=SCAN(COURSE,2);
RUN;

/* EXAMPLE12 */
DATA PATIENT_DATA;
PATIENT="Rahul Kumar Singh";
LAST_NAME=SCAN(PATIENT,3);
RUN;

/* EXAMPLE13 */
DATA VISIT_DATA;
VISIT="Visit 02 Screening";
VISIT_NO=SCAN(VISIT,2);
RUN;

/* EXAMPLE14 */
DATA HOSPITAL_DATA;
HOSPITAL="Apollo Hospital Chennai";
CITY=SCAN(HOSPITAL,3);
RUN;

/* EXAMPLE15 */
DATA COMPANY_DATA;
COMPANY="Tata Consultancy Services";
LAST_WORD=SCAN(COMPANY,3);
RUN;

/* EXAMPLE16 */
DATA COLLEGE_DATA;
COLLEGE="Delhi Technological University";
COLLEGE_NAME=SCAN(COLLEGE,2);
RUN;

/* EXAMPLE17 */
DATA COUNTRY_DATA;
LOCATION="New Delhi India";
COUNTRY=SCAN(LOCATION,3);
RUN;

/* EXAMPLE18 */
DATA DOCTOR_DATA;
DOCTOR="Dr Amit Kumar";
FIRST_NAME=SCAN(DOCTOR,2);
RUN;

/* EXAMPLE19 */
DATA DRUG_DATA;
DRUG="Paracetamol 500 Tablet";
STRENGTH=SCAN(DRUG,2);
RUN;

/* EXAMPLE20 */
DATA STUDY_DATA;
STUDY="Phase III Trial";
PHASE=SCAN(STUDY,2);
RUN;

/* EXAMPLE21 */
DATA SUBJECT_DATA;
SUBJECT="Clinical Data Management";
LAST_WORD=SCAN(SUBJECT,3);
RUN;

/* EXAMPLE22 */
DATA EMPLOYEE_DATA;
EMPLOYEE="Neha Sharma Manager";
DESIGNATION=SCAN(EMPLOYEE,3);
RUN;

/* EXAMPLE23 */
DATA PROJECT_DATA;
PROJECT="Base SAS Certification";
SECOND_WORD=SCAN(PROJECT,2);
RUN;

/* EXAMPLE24 */
DATA ADDRESS_DATA;
ADDRESS="Patna Bihar India";
STATE=SCAN(ADDRESS,2);
RUN;

/* EXAMPLE25 */
DATA UNIVERSITY_DATA;
UNIVERSITY="Ranchi University Jharkhand";
UNIVERSITY_NAME=SCAN(UNIVERSITY,2);
RUN;

/* EXAMPLE26 */
DATA TRAINING_DATA;
TRAINING="Clinical Research Program";
PROGRAM=SCAN(TRAINING,3);
RUN;

/* EXAMPLE27 */
DATA LANGUAGE_DATA;
LANGUAGE="SAS Programming Language";
LANGUAGE_NAME=SCAN(LANGUAGE,3);
RUN;

/* EXAMPLE28 */
DATA MEETING_DATA;
MEETING="Weekly Team Meeting";
TEAM_NAME=SCAN(MEETING,2);
RUN;

/* EXAMPLE28 */
DATA EXAMPLE28;
LANGUAGE=" I AM LEARNING SAS PROGRAMMING LANGUAGE";
EXATRACT=SCAN(LANGUAGE,-2);
RUN;

/* EXAMPLE29 */
DATA CONFERENCE_DATA;
CONFERENCE="Global Pharma Summit";
EVENT=SCAN(CONFERENCE,3);
RUN;

/* EXAMPLE30 */
DATA BOOK_DATA;
BOOK="Learning Base SAS";
BOOK_NAME=SCAN(BOOK,2);
RUN;



data patients;
input Patient_ID $ Patient_Name $20. Drug_Info $30.;
CARDS;
IND-001-RANCHI John_Smith Aspirin-500mg-Tablet
USA-002-NEWYORK Alice_Brown Paracetamol-650mg-Syrup
UK-003-LONDON David_Miller Ibuprofen-400mg-Capsule
;
run;
PROC PRINT DATA=PATIENTS;
RUN;

/* EXAMPLE31 */
DATA EXAMPLE31;
SET PATIENTS;
COUNTRY=SCAN(PATIENT_ID,2);
RUN;

/* EXAMPLE32 */
DATA EXAMPLE32;
SET PATIENTS;
NAME=SCAN(PATIENT_NAME,1);
RUN;

/* EXAMPLE33 */
DATA EXAMPLE33;
SET PATIENTS;
ID=SCAN(PATIENT_ID,2,"-");
RUN;

/* EXAMPLE34 */
DATA EXAMPLE34;
PATIENT_NO=SCAN(PATIENT_ID,2,"-");
RUN;

/* EXAMPLE35 */
DATA EXAMPLE35;
SET PATIENTS;
CITY=SCAN(PATIENT_ID,3,"-");
RUN;

/* EXAMPLE36 */
DATA EXAMPLE36;
SET PATIENTS;
DRUGNAME=SCN(DRUG_INFO,1,"-");
RUN;

/* EXAMPLE37 */
DATA EXAMPLE37;
SET PATIENTS;
DRUG_STRENGTH=SCAN(DRUG_INFO,2,"-");
RUN;

/* EXAMPLE38 */
DATA EXAMPLE38;
SET PATIENTS;
DOSAGE_FORM=SCAN(DRUG_INFO,3,"-");
RUN;

/* EXAMPLE39 */
DATA EXAMPLE39;
SET PATIENTS;
LASTVALUE=SCAN(PATIENT_ID,-1,"-");
RUN;

/* EXAMPLE40 */
DATA EXAMPLE40;
SET PATIENTS;
LAST_VALUE=SCAN(DRUG_INFO,-1,"-");
RUN;

/* EXAMPLE41 */
DATA EXAMPLE41;
SET PATIENTS;
SECOND_LAST_VALUE=SCAN(DRUG_INFO,2,"-");
RUN;

/* EXAMPLE42 */
DATA EXAMPLE42;
SET PATIENTS;
COUNTRY=SCAN(PATIENT_ID,1,"-");
RUN;

/* EXAMPLE43 */
DATA EXAMPLE43;
SET PATIENTS;
PATIENT_NO=SCAN(PATIENT_ID,2,"-");
RUN;

/* EXAMPLE44 */
DATA EXAMPLE44;
SET PATIENTS;
CITY=SCAN(PATIENT_ID,3,"-");
RUN;

/* EXAMPLE45 */
DATA EXAMPLE45;
SET PATIENTS;
DRUG_NAME=SCAN(DRUG_INFO,1,"-");
RUN;

/* EXAMPLE46 */
DATA EXAMPLE46;
SET PATIENTS;
STRENGTH=SCAN(DRUG_INFO,2,"-");
RUN;

/* EXAMPLE47 */
DATA EXAMPLE47;
SET PATIENTS;
DOSAGE_FORM=SCAN(PATIENT_INFO,3,"-");
RUN;

/* EXAMPLE48 */
DATA EXAMPLE48;
SET PATIENTS;
LOCATION=SCAN(PATIENT_ID,1-3,);
RUN;

/* EXAMPLE49 */
DATA EXAMPLE49;
SET PATIENTS;
DRUGLABEL=SCAN(DRUG_INFO,1,"-");
RUN;

/* EXAMPLE50 */
DATA EXAMPLE50;
SET PATIENTS;
SECOND_VALUE=SCAN(DRUG_INFO,2,"-");
RUN;

/* EXAMPLE51 */
DATA EXAMPLE51;
SET PATIENT;
FIRST_VALUE=SCAN(PATIENT_ID,-1,"-");
RUN;

/* EXAMPLE52 */
DATA EXAMPL52;
SET PATIENTS;
LAST_VALUE=SCAN(DRUG_INFO,-1,"-");

/* EXAMPLE53 */
DATA EXAMPLE53;
SET PATIENTS;
SECOND_VALUE=SCAN(PATIENT_ID,2,"-/");
RUN;

/* EXAMPLE54 */
DATA EXAMPLE54;
SET PATIENTS;
LASTVALUE=SCAN(PATIENT_NAME,1);
RUN;

/* EXAMPLE55 */
DATA EXAMPLE55;
SET PATIENTS;
FIRST_VALUE=SCAN(PATIENT_ID,1,"-");
RUN;

/* EXAMPLE56 */
DATA EXAMPLE56;
SET PATIENTS;
FIRST_VALUE=SCAN(DRUG_INFO,1,"-");
RUN;

/* EXAMPLE57 */
DATA EXAMPLE57;
SET PATIENTS;
LAST_VALUE=SCAN(DRUG_INFO,3,"-");
RUN;

/* EXAMPLE58 */
DATA EXAMPLE58;
SET PATIENTS;
ID _NO=SCAN(PATIENT_ID,2,"-");
RUN;

/* EXAMPLE59 */
DATA EXAMPLE59;
SET PATIENTS;
STRENGTH=SCAN(DRUG_INFO,2,"-");
RUN;

/* EXAMPLE60 */
DATA EXAMPLE60;
SET PATIENTS;
DRUG=SCAN(DRUG_INFO,1,"1");
RUN;

/* SUBSTR- IT HELP TO EXTRACT CHARACTER NOT WORD  */

/* EXAMPLE61 */
DATA EXAMPLE61;
NAME="SHRIKANT";
RESULT=SUBSTR(NAME,1,3);
RUN;

DATA HOSPITAL_RECORDS;
INPUT PATIENT_CODE $ ADMISSION_ID $ WARD_CODE $ DOCTOR_ID $ BED_NO $;
CARDS;
PAT1001 ADM250701 CAR301 DOC5001 B1201
PAT1002 ADM250702 NEU205 DOC5002 B1202
PAT1003 ADM250703 ICU101 DOC5003 B1203
;
RUN;

/* EXAMPLE62 */
DATA EXAMPLE62;
SET HOSPITAL_RECORDS;
PATIENT_PREFIX=SUBSTR(PATIENT_CODE,1,3);
RUN;

/* EXAMPLE63 */
DATA EXAMPLE63;
SET HOSPITAL_RECORDS;
PATIENT_N0=SUBSTR(PATIENT_CODE,4,4);
RUN;

/* EXAMPLE64 */
DATA EXAMPLE64;
SET HOSPITAL_RECORDS;
ADDMISSION_YR=SUBSTR(ADMISSION_ID,4,2);
RUN;

/* EXAMPLE65 */
DATA EXAMPLE65;
SET HOSPITAL_RECORDS;
ADMISSION_MONTH=SUBSTR(ADMISSION_ID,6,2);
RUN;

/* EXAMPLE66 */
DATA EXAMPLE66;
SET HOSPITAL_RECORDS;
ADMISSION_DAY=SUBSTR(ADMISSION_ID,8,2);
RUN;

/* EXAMPLE67 */
DATA EXAMPLE67;
SET HOSPITAL_RECORDS;
WARD_NO=SUBSTR(WARD_CODE,4,3);
RUN;

/* EXAMPLE68 */
DATA EXAMPLE68;
SET HOSPITAL_RECORDS;
WARD_LAST=SUBSTR(WARD_CODE,6);
RUN;


DATA LIFE_HOSPITAL;

INPUT PATIENT_CODE $ ADMISSION_ID $ WARD_CODE $ DOCTOR_ID $ BED_NO $;

CARDS;
PAT1001 ADM250701 CAR301 DOC5001 B1201
PAT1002 ADM250702 NEU205 DOC5002 B1202
PAT1003 ADM250703 ICU101 DOC5003 B1203
;
RUN;

/* EXAMPLE69 */
DATA PATIENT;
SET LIFE_HOSPITAL;
NUMERIC_PART=SUBSTR(PATIENT_CODE,4,4);
RUN;

/* EXAMPLE70 */
DATA WARD;
SET LIFE_HOSPITAL;
ALPHA_WARD_CODE=SUBSTR(WARD_CODE,1,3);
RUN;

/* EXAMPLE71 */
DATA YEARLY_REPORT;
SET LIFE_HOSPITAL;
ONLY_ADD_YR=SUBSTR(ADMISSION_ID,4,2);
RUN;

/* EXAMPLE72 */
DATA ADMISSION_REPOT;
SET LIFE_HOSPITAL;
ADMISSION_MONTH=SUBSTR(ADMISSION_ID,6,2);
RUN;

/* EXAMPLE73 */
DATA ADMISSION_REPORT;
SET LIFE_HOSPITAL;
ADMISSION_DATE=SUBSTR(ADMISSION_ID,8,2);
RUN;

/* EXAMPLE74 */
DATA DOCTOR_RECORD;
SET LIFE_HOSPITAL;
DOC_ID=SUBSTR(DOCTOR_ID,4,4);
RUN;

/* EXAMPLE75 */
DATA BED_RECORD;
SET LIFE_HOSPITAL;
BED_NO=SUBSTR(BED_NO,3,3);
RUN;

/* EXAMPLE76 */
DATA WRD_LIST;
SET LIFE_HOSPITAL;
WARD_ALPHA=SUBSTR(WARD_CODE,1,3);
RUN;

/* EXAMPLE77 */
DATA VERIFY_LIST;
SET LIFE_HOSPITAL;
VERIFY_PATIENT=SUBSTR(PATIENT_CODE,1,3);
RUN;

/* EXAMPLE78 */
DATA MISSED_ID;
SET LIFE_HOSPITAL;
REMAINING_LABEL=SUBSTR(PATIENT_CODE,1,3);
RUN;

/* EXAMPLE79 */
DATA REPORT;
SET LIFE_HOSPITAL;
DOCTOR_WISE_REPORT=SUBSTR(DOCTOR_ID,4,4);
RUN;

/* EXAMPLE80 */
DATA BED_RECORD;
SET LIFE_HOSPITAL;
BED_FLOOR=SUBSTR(BED_NO,4,2);
RUN;

/* EXAMPLE81 */
DATA ADMISSION_REPORT;
SET LIFE_HOSPITAL;
YEAR_MONTH_ONLY=SUBSTR(ADMISSION_ID,4,4);
RUN;

/* EXAMPLE82 */
DATA IT_RECORDS;
SET LIFE_HOSPITAL;
INDEXING_ID=SUBSTR(ADMISSION_ID,1,4);
RUN;

/* EXAMPLE83 */
DATA DOCTOR_ID;
SET LIFE_HOSPITAL;
EXTRACT=SUBSTR(DOCTOR_ID,3,4);
RUN;

/* EXAMPLE84 */
DATA PATIENT_LIST;
SET LIFE_HOSPITAL;
PATIENT_NO=SUBSTR(PATIENT_CODE,4,4);
RUN;

/* EXAMPLE85 */
DATA WARD_DETAILS;
SET LIFE_HOSPITAL;
WARD_NUMBER=SUBSTR(WARD_CODE,4,3);
RUN;

/* EXAMPLE86 */
DATA EXAMPLE51;
SET PATIENT;
FIRST_VALUE=SCAN(PATIENT_ID,4,6);
RUN;

/* EXAMPLE87 */
DATA EXAMPL52;
SET PATIENTS;
LAST_VALUE=SCAN(DRUG_INFO,-1,4);

/* EXAMPLE88 */
DATA EXAMPLE53;
SET PATIENTS;
SECOND_VALUE=SCAN(PATIENT_ID,2,4);
RUN;

/* EXAMPLE89 */
DATA EXAMPLE54;
SET PATIENTS;
LASTVALUE=SCAN(PATIENT_NAME,1,2);
RUN;

/* EXAMPLE90 */
DATA EXAMPLE55;
SET PATIENTS;
FIRST_VALUE=SCAN(PATIENT_ID,1,5);
RUN;

DATA EMPLOYEE_MASTER;
INPUT EMPLOYEE_ID $ DEPARTMENT_CODE $ EMAIL_ID $ DESIGNATION_CODE $ EMP_STATUS $;
DATALINES;
EMP1001 HRD101 JOHN.SMITH@ABC.COM MGR001 ACT2025
EMP1002 FIN205 ALICE.BROWN@ABC.COM ANA002 INA2024
EMP1003 ITS310 DAVID.MILLER@ABC.COM DEV003 ACT2025
EMP1004 MKT420 EMMA.WILSON@ABC.COM EXE004 SUS2026
EMP1005 QAC510 ROBERT.TAYLOR@ABC.COM TST005 ACT2025
;
RUN;

/* EXAMPLE91 */
DATA EXAMPLE91;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,1,3)="STA";
RUN;

/* EXAMPLE92 */
DATA EXAMPLE92;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,4,4)="9001";
RUN;

/* EXAMPLE93 */
DATA EXAMPLE93;
SET EMPLOYEE_MASTER;
SUBSTR(DEPARTMENT_CODE,1,3)="DEP";
RUN;

/* EXAMPLE94 */
DATA EXAMPLE94;
SET EMPLOYEE_MASTER;
SUBSTR(DESIGNATION_CODE,1,3)="JOB";
RUN;

/* EXAMPLE95 */
DATA EMAMPLE95;
SET EMPLOYEE_MASTER;
SUBSTR(EMAIL_ID,11,7)="XYZ.ORG";
RUN;

/* EXAMPLE96 */
DATA EXAMPLE96;
SET EMPLOYEE_MASTER;
SUBSTR(EMP_STATUS,4,4)="2030";
RUN;

/* EXAMPLE97 */
DATA EXAMPLE97;
SET EMPLOYEE_MASTER;
SUBSTR(DEPARTMENT_CODE,4,3)="777";
RUN;

/* EXAMPLE98 */
DATA EXAMPLE98;
SET EMPLOYEE_MASTER;
SUBSTR(DEPARTMENT_CODE,4,3)="101";
RUN;

/* EXAMPLE99 */
DATA EXAMPLE99;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,4,4)="5000";
RUN;

/* EXAMPLE100 */
DATA EXAMPLE100;
SET EMPLOYEE_MASTER;
SUBSTR(EMAIL_ID,1,4)="USER";
RUN;

/* EXAMPLE101 */
DATA EXAMPLE101;
SET EMPLOYEE_MASTER;
SUBSTR(DEPARTMENT_CODE,1,3)="MEW";
RUN;

/* EXAMPLE102 */
DATA EXAMPLE102;
SET EMPLOYEE_MASTER;
SUBSTR(EMP_STATUS,1,3)="APR";
RUN;

/* EXAMPLE103 */
DATA EXAMPLE103;
SET EMPLOYEE_MASTER;
SUBSTR(EMAIL_ID,1,4)="TEST";
RUN;

/* EXAMPLE104 */
DATA EXAMPLE104;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,1,6)="STA999";
RUN;

/* EXAMPLE105 */
DATA EXAMPLE105;
SET EMPLOYEE_MASTER;
SUBSTR(DESIGNATION_CODE,1,2)="XX";
RUN;

/* EXAMPLE106 */
DATA EXAMPLE106;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,1,3)="ABC";
RUN;

/* EXAMPLE107 */
DATA EXAMPLE107;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,1,3)="WRK";
RUN;

/* EXAMPLE107 */
DATA EXAMPLE107;
SET EMPLOYEE_MASTER;
SUBSTR(EMP_STATUS,1,1)="P";
RUN;

/* EXAMPLE108 */
DATA EXAMPLE108;
SET EMPLOYEE_MASTER;
SUBSTR(EMP_STATUS,6,2)="30";
RUN;

/* EXAMPLE109 */
DATA EXAMPLE109;
SET EMPLOYEE_MASTER;
SUBSTR(EMAIL_ID,1,5)="STAFF";
RUN;

/* EXAMPLE110 */
DATA EXAMPLE110;
SET EMPLOYEE_MASTER;
SUBSTR(EMAIL_ID,12,3)="XYZ";
RUN;

/* EXAMPLE111 */
DATA EXAMPLE111;
SET EMPLOYEE_MASTER;
SUBSTR(EMAIL_ID,16,3)="ORG";
RUN;

/* EXAMPLE112 */
DATA EXAMPLE112;
SET EMPLOYEE_MASTER;
SUBSTR(DEPARTMENT_CODE,1,1)="X";
RUN;

/* EXAMPLE113 */
DATA EXAMPLE113;
SET EMPLOYEE_MASTER;
SUBSTR(DESIGNATION_CODE,6,1)="8";
RUN;

/* EXAMPLE114 */
DATA EXAMPLE114;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,5,3)="555";
RUN;

/* EXAMPLE115 */
DATA EXAMPLE115;
SET EMPLOYEE_MASTER;
SUBSTR(EMP_STATUS,2,2)="XX";
RUN;

/* EXAMPLE116 */
DATA EXAMPLE116;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,1,2)="HR";
RUN;

/* EXAMPLE117 */
DATA EXAMPLE117;
SET EMPLOYEE_MASTER;
SUBSTR(DEPARTMENT_CODE,4,3)="888";
RUN;

/* EXAMPLE118 */
DATA EXAMPLE118;
SET EMPLOYEE_MASTER;
SUBSTR(EMP_STATUS,1,3)="TMP";
RUN;

/* EXAMPLE119 */
DATA EXAMPLE119;
SET EMPLOYEE_MASTER;
SUBSTR(EMPLOYEE_ID,4,4)="1234";
RUN;

/* EXAMPLE120 */
DATA EXAMPLE120;
SET EMPLOYEE_MASTER;
SUBSTR(DESIGNATION_CODE,1,5)="LEAD9";
RUN;

DATA INTRO;
NAME="SHRI170604 IS A VERY INTROVERT";
SUBSTR(NAME,7,4)="2026";
RUN;


