/* TASK 7  */
/* DSD- 10 EXAMPLES */
/* DLM- 10  EXAMPLES */
/* TRUNCOVER/FLOWOVER- 20 EXAMPLES */
/* STOPOVER- 20 EXAMPLE */
/* SCANOVER-20 EXAMPLES */

/* DSD- DATA SEPERATED DELIMETER */
/* HELPS TO REMOVE , FROM THE DATASET */

LIBNAME SHRIKANT "/home/u64536648/PRACTICE INFILE DATASET";

/* EXAMPLE 1 */
DATA SHRIKANT.BOOKSLIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/books_dataset_comma.txt" DSD;
INPUT BOOK_ID $ TITLE $ AUTHOR $ TYPE $ YEAR;
RUN;

/* EXAMPLE 2 */
DATA SHRIKANT.COSTUMER_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/customers_dataset_comma.txt" DSD;
INPUT COSTUMER_ID $ NAME $ STATE $ GENDER $ AGE;
RUN;

/* EXAMPLE 3 */
DATA SHRIKANT.EMPLOYEE_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/customers_dataset_comma.txt" DSD;
INPUT EMP_ID $ NAME $ DEPARTMENT $ AGE SALARY;
RUN;

/* EXAMPLE 4 */
DATA SHRIKANT_FLIGHT_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/flights_dataset_comma.txt" DSD;
INPUT FLIGHT_ID $ AIRLINES $ FROM $ TO $ STATUS;
RUN;

/* EXAMPLE 5 */
DATA SHRIKANT.HOSPITAL_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/hospitals_dataset_comma.txt" DSD;
INPUT HOSPITAL_ID $ NAME $ LOCATION $ BEDS RATINGS;
RUN;

/* EXAMPLE 6 */
DATA SHRIKANT.MOVIES_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/movies_dataset_comma.txt" DSD;
INPUT MOVIE_ID $ NAME $ TYPE $ LANGUAGE $ RATINGS;
RUN;

/* EXAMPLE 7 */
DATA SHRIKAT.ORDER_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/orders_dataset_comma.txt" DSD;
INPUT ORDER_ID $ COSTUMER $ PRODUCT $ ORDER STATUS $;
RUN;

/* EXAMPLE 8 */
DATA SHRIKANT.PRODUCT_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/products_dataset_comma.txt" DSD;
INPUT PRODUCT_ID $ PROCUCT $ ITEM $ QTY LEFT;
RUN;

/* EXAMPLE 9 */
DATA SHRIKANT.STUDENTS_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/students_dataset_comma.txt" DSD;
INPUT STUDENT_ID $ NAME $ SUBJECT $ YEAR GRADE $;
RUN;

/* EXAMPLE 10 */
DATA SHRIKANT.VEHICHE_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/vehicles_dataset_comma.txt" DSD;
INPUT V_ID $ BRAND $ MODEL $ YEAR COLOUR $;
RUN;

/* DLM DELIMETER LIKE /@\| */

/* EXAMPLE 1 */
DATA SHRIKANT.COURIOR_RECORD;
INFILE "/home/u64536648/DLM DATA SET/courier_unknown.txt" DLM='~';
INPUT TRACKING_ID $ SOURCE $ FROM $ STATUS $ RATINGS;
RUN;

/* EXAMPLE 2 */
DATA SHRIKANT.ELECTRICITY_RECORD;
INFILE "/home/u64536648/DLM DATA SET/electricity_unknown.txt" DLM=';';
INPUT BILL_ID $ BILL_NO AMOUNT STATUS $ DATE $;
RUN;

/* EXAMPLE 3 */
DATA SHRIKANT.EMPLOYEE_RECORD;
INFILE "/home/u64536648/DLM DATA SET/employees_noheader.txt" DLM=',';
INPUT ID $ NAME $ DEPARTENT $ SALARY STATE $;
RUN;

/* EXAMPLE 4 */
DATA SHRIKANT.LIBRARY_RECORDS;
INFILE "/home/u64536648/DLM DATA SET/library_unknown.txt" DLM='|';
INPUT BOOKK_ID $ NAME $ BOOKS_TAKEN DATE $ STATUS $;
RUN;

/* EXAMPLE 5 */
DATA SHRIKANT.MIX1;
INFILE "/home/u64536648/DLM DATA SET/mix_dlm_1.txt" DLM=',;|';
INPUT ID  NAME $ DEPARTMENT $ LOCATION $ SALARY;
RUN;

/* EXAMPLE 6 */
DATA SHRIKANT.SPORTS_RECORD;
INFILE "/home/u64536648/DLM DATA SET/sports_unknown.txt" DLM=',';
INPUT NAME $ RUN BALL SIX FOUR;
RUN;

/* EXAMPLE 7 */
DATA SHRIKANT.WEATHER_REPORT;
INFILE "/home/u64536648/DLM DATA SET/weather_unknown.txt" DLM=',';
INPUT TEMP_C TEMP_F WEATHER $ STATE $ PART ;
RUN;

/* EXAMPLE 8 */
DATA SHRIKANT.BANKING_RECORD;
INFILE "/home/u64536648/DLM DATA SET/BANKING MIXED.txt" DLM=',|;~';
INPUT TRANSACTION_ID $ BANK $ AMOUNT STATUS $ STATE $;
RUN;

/* EXAMPLE 9 */
DATA SHRIKANT.ORDER_LIST;
INFILE "/home/u64536648/DLM DATA SET/ORDER_DATA.txt" DLM=',|;~';
INPUT ORDER_ID $ ITEM $ TYPE $ STATUS $ LOCATION $;
RUN;

/* EXAMPLE 10 */
DATA SHRIKANT.PHARAMACY_RECORD;
INFILE "/home/u64536648/DLM DATA SET/PHARMACY.txt" DLM=',|~;';
INPUT MED_ID $ MEDICINE $ DOSAGE $ POWER $ AVAILABLITY $;
RUN;

/* TRUNCOVER/FLOWOVER-20 EXAMPLES */

/* EXAMPLE 1 */
DATA SHRIKANT.EMPLOYEE_T;
INFILE "/home/u64536648/DLM DATA SET/EMPLOYEE TRUN.txt" DLM=',' TRUNCOVER;
INPUT ID NAME $ DEPARTMENT $ STATE $ SALARY;
RUN;

/* EXAMPLE 2 */
DATA SHRIKANT.STUDENT_T;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/STUDENT_TRUN.txt" DLM=',' TRUNCOVER;
INPUT STUDENT_ID $ NAME $ COURSE $ YEAR GRADE $;
RUN;

/* EXAMPLE 3 */
DATA SHRIKANT.COUIOUR_REORD;
INFILE CARDS TRUNCOVER;
INPUT ID $1-3 LOCATION $ 5-8 SHIPMENT $ 10-19;
CARDS;
C01 DEL	 Packed
C02	MUM
C03
C04	BLR	 Shipped
C05	HYD
C06
C07	PNQ	 Out
C08	RNC
C09
C10	LKO	 Delivered
;
RUN;

/* EXAMPLE 4 */
DATA SHRIKANT.CRICKET_SCORE;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/cricket_score_02.txt" DLM=',' TRUNCOVER;
INPUT ID $ NAME $ RUN BALL SIX;
RUN;

/* EXAMPLE 5 */
DATA SHRIKANT.FOOD_LIST;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/food_06.txt" DLM='|' TRUNCOVER;
INPUT O_NO $ ITEM $ ORDER PAYMENT $;
RUN;

/* EXAMPLE 6  */
DATA SHRIKANT.METER_RECORD;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/meter_04.txt" DLM='^' TRUNCOVER;
INPUT METER_ID $ NO DISTANCE STATUS $;
RUN;

/* EXAMPLE 7 */
DATA SHRIKANT.PASSPORT_RECORD;
INFILE CARDS 
DSD TRUNCOVER;
INPUT ID $ NAME $ COUNTRY $ GENDER $;
CARDS;
A1,Anil,IND
A2,Sara
A3
A4,Riya,IND,F
A5
A6,John
A7
A8,Asha,IND
A9
A10,Ram
;
RUN;

/* EXAMPLE 8 */
DATA SHRIKANT.RAILWAY_DETAILS;
INFILE CARDS DLM='~' TRUNCOVER;
INPUT PASSENGER_ID $ NAME $ DESTINATION $ FROM $ TYPE $;
CARDS;
P1~Raj~RNC~NDLS~SL
P2~Amit~PNBE
P3
P4~Neha~LKO~CNB
P5~Sara~BPL~NGP~3A
P6~Ravi
P7~Kiran~MAS
P8
P9~Asha~HWH~RNC
P10~Deep
;
RUN;

/* EXAMPLE 9 */
DATA SHRIKANT.TOLL_LIST;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/toll_08.txt" DLM='|' TRUNCOVER;
INPUT TOLL_ID $ VEHICLE $ AMOUNT
RUN;

/* EXAMPLE 10 */
DATA SHRIKANT.WEATHER_REPORT;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/weather_station_01.txt" DLM='|' TRUNCOVER;
INPUT STATION_ID $ STATE $ TEMP AMOUNT YEAR;
RUN;


/*=============================== FLOWOVER ========================================== */

/* EXAMPLE 1 */
DATA SHRIKANT.AIRPORT_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_airport_07.txt" FLOWOVER;
INPUT AIRPORT_ID $ NAME $ CITY $ BATCH_NO STATUS $;
RUN;

/* EXAMPLE 2 */
DATA SHRIKANT.BOOKS_LIST;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_books_02.txt" FLOWOVER;
INPUT BOOK_ID $ NAME $ PRICE;
RUN;

/* EXAMPLE 3 */
DATA SHRIKANT.CLINIC_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_clinic_01.txt" FLOWOVER;
INPUT CLINIC_ID $ NAME $ CITY $ ROOM_No STATUS $;
RUN;

/* EXAMPLE 4 */
DATA SHRIKANT.HOSPITAL_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_hospital_big.txt" FLOWOVER;
INPUT PATIENT_ID $ NAME $ CITY $ AGE EXTRA $;
RUN;

/* EXAMPLE 5 */
DATA SHRIKANT.HOTEL_ROOMS;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_hotel_06.txt" FLOWOVER;
INPUT HOTEL_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 6 */
DATA SHRIKANT.ISURANCE_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_insurance_05.txt" FLOWOVER;
INPUT INSURANE_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 7 */
DATA SHRIKANT.LIBRARY_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_library_09.txt" FLOWOVER;
INPUT BOOK_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 8 */
DATA SHRIKANT.PHARMACY_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_pharmacy_08.txt" FLOWOVER;
INPUT PATIENT_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 9 */
DATA SHRIKANT.TELECOME_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_telecom_04.txt" FLOWOVER;
INPUT TELE_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 10 */
DATA SHRIKANT.UNIVERSITY_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_university_02.txt" FLOWOVER;
INPUT UNIVERSITY_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* STOPOVER -STOPOVER tells SAS to stop the DATA step immediately  */
/* if it reaches the end of a line before reading all the variables. */

/* EXAMPLE 1 */
DATA SHRIKANT.EMPLOYEE_T;
INFILE "/home/u64536648/DLM DATA SET/EMPLOYEE TRUN.txt" DLM=',' STOPOVER;
INPUT ID NAME $ DEPARTMENT $ STATE $ SALARY;
RUN;

/* EXAMPLE 2 */
DATA SHRIKANT.STUDENT_T;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/STUDENT_TRUN.txt" DLM=',' STOPOVER;
INPUT STUDENT_ID $ NAME $ COURSE $ YEAR GRADE $;
RUN;

/* EXAMPLE 3 */
DATA SHRIKANT.COUIOUR_REORD;
INFILE CARDS STOPOVER;
INPUT ID $1-3 LOCATION $ 5-8 SHIPMENT $ 10-19;
CARDS;
C01 DEL	 Packed
C02	MUM
C03
C04	BLR	 Shipped
C05	HYD
C06
C07	PNQ	 Out
C08	RNC
C09
C10	LKO	 Delivered
;
RUN;

/* EXAMPLE 4 */
DATA SHRIKANT.CRICKET_SCORE;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/cricket_score_02.txt" DLM=',' STOPOVER;
INPUT ID $ NAME $ RUN BALL SIX;
RUN;

/* EXAMPLE 5 */
DATA SHRIKANT.FOOD_LIST;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/food_06.txt" DLM='|' STOPOVER;
INPUT O_NO $ ITEM $ ORDER PAYMENT $;
RUN;

/* EXAMPLE 6  */
DATA SHRIKANT.METER_RECORD;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/meter_04.txt" DLM='^' STOPOVER;
INPUT METER_ID $ NO DISTANCE STATUS $;
RUN;

/* EXAMPLE 7 */
DATA SHRIKANT.PASSPORT_RECORD;
INFILE CARDS 
DSD STOPOVER;
INPUT ID $ NAME $ COUNTRY $ GENDER $;
CARDS;
A1,Anil,IND
A2,Sara
A3
A4,Riya,IND,F
A5
A6,John
A7
A8,Asha,IND
A9
A10,Ram
;
RUN;

/* EXAMPLE 8 */
DATA SHRIKANT.RAILWAY_DETAILS;
INFILE CARDS DLM='~' STOPOVER;
INPUT PASSENGER_ID $ NAME $ DESTINATION $ FROM $ TYPE $;
CARDS;
P1~Raj~RNC~NDLS~SL
P2~Amit~PNBE
P3
P4~Neha~LKO~CNB
P5~Sara~BPL~NGP~3A
P6~Ravi
P7~Kiran~MAS
P8
P9~Asha~HWH~RNC
P10~Deep
;
RUN;

/* EXAMPLE 9 */
DATA SHRIKANT.TOLL_LIST;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/toll_08.txt" DLM='|' STOPOVER;
INPUT TOLL_ID $ VEHICLE $ AMOUNT
RUN;

/* EXAMPLE 10 */
DATA SHRIKANT.WEATHER_REPORT;
INFILE "/home/u64536648/DLM DATA SET/TRUNCOVER FLOWOVER/weather_station_01.txt" DLM='|' STOPOVER;
INPUT STATION_ID $ STATE $ TEMP AMOUNT YEAR;
RUN;

/* EXAMPLE 11 */
DATA SHRIKANT.DRUG_RECORD;
INFILE CARDS STOPOVER;
INPUT DRUG_ID $ NAME $ DOSE POWER STATE $;
CARDS;
P501 Crocin 10 35 Delhi
P502 Amoxicillin 5 210 Mumbai
P503 Cetirizine 12 48 Pune
P504 Insulin
P505 Paracetamol 20 72 Ranchi
P506 Azithromycin 8 360 Kolkata
P507 Pantoprazole 15 420 Delhi
P508 Metformin 30 180 Chennai
P509 Dolo650 25 125 Patna
P510 VitaminC 40 200 Jaipur
;
RUN;

/* EXAMPLE 12 */
DATA SHRIKANT.BOOK_RECORD;
INFILE CARDS STOPOVER;
INPUT BOOK_ID $ NAME $ AUTHOR $ YEAR REMARKS $;
CARDS;
L901 CleanCode RobertMartin 2024 Issued
L902 SASGuide ChrisHemedinger 2023 Returned
L903 SQLCookbook AnthonyMolinaro
L904 PythonCrashCourse EricMatthes 2022 Issued
L905 HeadFirstJava KathySierra 2021 Returned
L906 EffectiveJava JoshuaBloch 2019 Issued
L907 LearningSAS RonCody 2020 Returned
L908 DataAnalytics JamesMiller 2023 Issued
L909 LinuxBasics JasonCannon 2018 Returned
L910 MachineLearning AurélienGéron 2024 Issued
;
RUN;

/* EXAMPLE 13 */
DATA SHRIKANT.AIRPORT_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_airport_07.txt" STOPOVER;
INPUT AIRPORT_ID $ NAME $ CITY $ BATCH_NO STATUS $;
RUN;

/* EXAMPLE 14 */
DATA SHRIKANT.BOOKS_LIST;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_books_02.txt" STOPOVER;
INPUT BOOK_ID $ NAME $ PRICE;
RUN;

/* EXAMPLE 15 */
DATA SHRIKANT.CLINIC_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_clinic_01.txt" STOPOVER;
INPUT CLINIC_ID $ NAME $ CITY $ ROOM_No STATUS $;
RUN;

/* EXAMPLE 16 */
DATA SHRIKANT.HOSPITAL_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_hospital_big.txt" STOPOVER;
INPUT PATIENT_ID $ NAME $ CITY $ AGE EXTRA $;
RUN;

/* EXAMPLE 17 */
DATA SHRIKANT.HOTEL_ROOMS;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_hotel_06.txt" STOPOVER;
INPUT HOTEL_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 18 */
DATA SHRIKANT.ISURANCE_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_insurance_05.txt" STOPOVER;
INPUT INSURANE_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 19 */
DATA SHRIKANT.LIBRARY_RECORD;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_library_09.txt" STOPOVER;
INPUT BOOK_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* EXAMPLE 20 */
DATA SHRIKANT.PHARMACY_R;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/flowover_pharmacy_08.txt" FLOWOVER STOPOVER;
INPUT PATIENT_ID $ NAME $ CITY $ NO STATUS $;
RUN;

/* SCANOVER -Instead of reading data by position, */
/*  SAS first looks for a keyword, then reads the value that comes after it. */

/* EXAMPLE 1 */
DATA SHRIKANT.SCAN1;
INFILE CARDS SCANOVER;
INPUT @'RAHUL' ID COURSE $;
CARDS;
10 RAHUL 101 SAS
20 AMIT 102 SQL
30 RAHUL 103 PYTHON
40 PRIYA 104 R
50 RAHUL 105 EXCEL
;
RUN;

/* EXAMPLE 2 */
DATA SHRIKANT.SCAN2;
INFILE CARDS SCANOVER;
INPUT @' CAT' COLOUR $;
CARDS;
101 CAT RED
102 DOG BLACK
103 CAT WHITE
104 LION BROWN
105 CAT GREY
;
RUN;

/* EXAMPLE 3 */
DATA SHRIKANT.SCAN3;
INFILE CARDS SCANOVER;
INPUT @'APPLE' QTY;
CARDS;
11 APPLE 250
12 MANGO 300
13 ORANGE 180
14 APPLE 400
15 BANANA 150
;
RUN;

/* EXAMPLE 4 */
DATA SHRIKANT.SCAN4;
INFILE CARDS SCANOVER;
INPUT @'DAVID' DEPARTMENT $;
CARDS;
501 JOHN HR
502 DAVID IT
503 JOHN SALES
504 RAHUL FINANCE
505 JOHN ADMIN
;
RUN;

/* EXAMPLE 5 */
DATA SHRIKANT.SCAN5;
INFILE CARDS SCANOVER;
INPUT @'DELHI' DIRECTION $;
CARDS;
1 DELHI NORTH
2 MUMBAI WEST
3 DELHI SOUTH
4 CHENNAI EAST
5 DELHI CENTRAL
;
RUN;

/* EXAMPLE 6 */
DATA SHRIKANT.SCAN6;
INFILE "/home/u64536648/DLM DATA SET/FLOWOVER DATASET/SCAN 6.txt" SCANOVER;
INPUT @'RAHUL' NO PROGRAM $ LOCATION $ BATCH $ SHIFT $ REMARKS $;
RUN;

/* EXAMPLE 7 */
DATA SHRIKANT.SCAN7;
INFILE CARDS SCANOVER;
INPUT @'MOBILE' BRAND $ PRICE AVAILABLITY $;
CARDS;
1001 MOBILE SAMSUNG 25000 AVAILABLE
1002 LAPTOP DELL 55000 SOLD
1003 MOBILE APPLE 70000 AVAILABLE
1004 TV SONY 48000 SOLD
1005 MOBILE VIVO 18000 AVAILABLE
1006 MOBILE OPPO 21000 SOLD
1007 LAPTOP HP 62000 AVAILABLE
1008 MOBILE REALME 17000 AVAILABLE
1009 TV LG 52000 SOLD
1010 MOBILE ONEPLUS 39000 AVAILABLE
;
RUN;

/* EXAMPLE 8 */
DATA SHRIKANT.SCAN8;
INFILE CARDS SCANOVER;
INPUT @'CAR' BRAND $ COLOR $ STATUS $;
CARDS;
701 CAR HONDA RED SOLD
702 BIKE TVS BLACK AVAILABLE
703 CAR SUZUKI WHITE SOLD
704 TRUCK TATA BLUE AVAILABLE
705 CAR HYUNDAI GREY SOLD
706 CAR MAHINDRA BLACK AVAILABLE
707 BIKE HONDA RED SOLD
708 CAR TOYOTA WHITE AVAILABLE
709 BUS ASHOKLEYLAND YELLOW SOLD
710 CAR KIA BLUE AVAILABLE
;
RUN;

/* EXAMPLE 11 */
DATA SHRIKANT.SCAN11;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/books_dataset_comma.txt" SCANOVER;
INPUT @'DRAMA' YEAR;
RUN;

/* EXAMPLE 12 */
DATA SHRIKANT.SCAN12;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/customers_dataset_comma.txt" scanover;
INPUT  @'PUNE' $ GENDER $ AGE;
RUN;

/* EXAMPLE 13 */
DATA SHRIKANT.EMPLOYEE_LIST;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/customers_dataset_comma.txt" SCANOVER;
INPUT @'IT' AGE SALARY;
RUN;

/* EXAMPLE 14 */
DATA SHRIKANT_SCAN14;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/flights_dataset_comma.txt" SCANOVER;
INPUT @'VISTARA' FROM $ TO $ STATUS;
RUN;

/* EXAMPLE 15 */
DATA SHRIKANT.SCAN15;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/hospitals_dataset_comma.txt" SCANOVER;
INPUT @ 'RANCHI' BEDS RATINGS;
RUN;

/* EXAMPLE 16 */
DATA SHRIKANT.SCAN16;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/movies_dataset_comma.txt" SCANOVER;
INPUT @'MARATHI'RATINGS;
RUN;

/* EXAMPLE 17 */
DATA SHRIKAT.SCAN17;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/orders_dataset_comma.txt" SCANOVER;
INPUT @'LAPTOP'ORDER STATUS $;
RUN;

/* EXAMPLE 18 */
DATA SHRIKANT.SCAN18;
INFILE "/home/u64536648/PRACTICE INFILE DATASET/products_dataset_comma.txt" SCANOVER;
INPUT PRODUCT_ID $ PROCUCT $ ITEM $ QTY LEFT;
RUN;

/* EXAMPLE 19 */
DATA SHRIKANT.SCAN19;
INFILE CARDS SCANOVER;
INPUT @'FEVER' DR_NAME $ IPD_OPD $;
CARDS;
501 RAHUL FEVER DRSHARMA ADMIT
502 PRIYA MIGRAINE DRKHAN DISCHARGE
503 AMIT DIABETES DRPATEL ADMIT
504 RAHUL ASTHMA DRROY ADMIT
505 SONIA FEVER DRGUPTA DISCHARGE
506 RAHUL DENGUE DRMEHTA ADMIT
507 KUNAL TYPHOID DRSINGH ADMIT
508 RAHUL COVID DRKHAN DISCHARGE
509 NEHA MALARIA DRPATEL ADMIT
510 RAHUL FEVER DRROY ADMIT
;
RUN;

/* EXAMPLE 20 */
DATA SHRIKANT.SCAN20;
INFILE CARDS SCANOVER;
INPUT @'CAR' BRAND $ COLOR $ STATUS $;
CARDS;
701 CAR HONDA RED SOLD
702 BIKE TVS BLACK AVAILABLE
703 CAR SUZUKI WHITE SOLD
704 TRUCK TATA BLUE AVAILABLE
705 CAR HYUNDAI GREY SOLD
706 CAR MAHINDRA BLACK AVAILABLE
707 BIKE HONDA RED SOLD
708 CAR TOYOTA WHITE AVAILABLE
709 BUS ASHOKLEYLAND YELLOW SOLD
710 CAR KIA BLUE AVAILABLE
;
RUN;
