/* Date -30/06/2026 */
/* Topic - Infile statment */

/* 10 EXAMPLES OF INFILE STATMENT */
LIBNAME SAHU "/home/u64536648/DAILY TASK";
/* EXAMPLE 1 */
DATA SAHU.EMPLOYEE_RECORD;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt";
INPUT EMP_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 2 */
DATA SAHU.MARKS_RECORD;
INFILE "/home/u64536648/AI GURU/students.txt";
INPUT STUD_ID $ NAME $ SUBJECT $ YEAR CGPA;
RUN;

/* EXAMPLE 3 */
DATA SAHU.HOSPITAL_LIST;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt";
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 4 */
DATA SAHU.SALES_LAPTOP;
INFILE "/home/u64536648/AI GURU/sales.txt";
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 5 */
DATA SAHU.BANK_DETAILS;
INFILE "/home/u64536648/AI GURU/bank.txt";
INPUT ACCOUYNT_ID $ NAME $ TYPE $ AMOUNT STATE $;
RUN;

/* EXAMPLE 6 */
DATA SAHU.LIBRARY_RECORDS;
INFILE "/home/u64536648/AI GURU/library.txt";
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;

/* EXAMPLE 7 */
DATA SAHU.MOVIES_RECORD;
INFILE "/home/u64536648/AI GURU/movies.txt";
INPUT MOVIE_ID $ TITLE $ TYPE $ YEAR RATING;
RUN;

/* EXAMPLE 8 */
DATA SAHU.PRODUCT_DETAILS;
INFILE "/home/u64536648/AI GURU/products.txt";
INPUT PRODUCT_ID $ PRODUCT $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 9 */
DATA SAHU.PATIENT_DETAILS;
INFILE "/home/u64536648/AI GURU/patients.txt";
INPUT PATIENT_ID $ NAME $ AGE DISEASE $ WARD $;
RUN;

/* EXAMPLE 10 */
DATA SAHU.FLIGHT_DETAILS;
INFILE "/home/u64536648/AI GURU/flights.txt";
INPUT FLIGHT_ID $ COMPANY $ FROM $ TO $ PRICE;
RUN;

/* 40 examples of infile statment with firstrow option */

/* EXAMPLE 1 */
DATA SAHU.BANK_STATMENTS;
INFILE "/home/u64536648/AI GURU/bank.txt" FIRSTOBS=3;
INPUT ACCOUYNT_ID $ NAME $ TYPE $ AMOUNT STATE $;
RUN;

/* EXAMPLE 2 */
DATA SAHU.CLINIHUNT_FILE;
INFILE "/home/u64536648/AI GURU/CLINIH.txt" FIRSTOBS=2;
INPUT ID BRANCH $ MARKS RESULT $;
RUN;

/* EXAMPLE 3 */
DATA SAHU. EMPOYEE_RECORDINGS;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" FIRSTOBS=4;
INPUT EPLPYEE_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 4 */
DATA SAHU.FLIGHT_PRICES;
INFILE "/home/u64536648/AI GURU/flights.txt" FIRSTOBS=3;
INPUT FLIGHT_ID $ COMPANY $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 5  */
DATA SAHU.HOSPITALS_RECORDS;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" FIRSTOBS=2;
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 6 */
DATA SAHU.LIBRARY_RECORDS;
INFILE "/home/u64536648/AI GURU/library.txt" FIRSTOBS=4;
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;

/* EXAMPLE 7 */
DATA SAHU.MOVIES_ROOM;
INFILE "/home/u64536648/AI GURU/movies.txt" FIRSTOBS=3;
INPUT MOVIE_ID $ TITLE $ TYPE $ YEAR RATING;
RUN;

/* EXAMPLE 8 */
DATA SAHU.PATIENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/patients.txt" FIRSTOBS=5;
INPUT PATIENT_ID $ NAME $ AGE DISEASE $ WARD $;
RUN;

/* EXAMPLE 9 */
DATA SAHU.PRODUCTS_RECORD;
INFILE "/home/u64536648/AI GURU/products.txt" FIRSTOBS=4;
INPUT PRODUCT_ID $ PRODUCT $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 10  */
DATA SAHU.SALES_RECORD;
INFILE "/home/u64536648/AI GURU/sales.txt" FIRSTOBS=2;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 11 */
DATA SAHU.STUDENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/students.txt" FIRSTOBS=3;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 12 */
DATA SAHU.BANK_CROUP;
INFILE "/home/u64536648/AI GURU/bank.txt" FIRSTOBS=2;
INPUT ACCOUYNT_ID $ NAME $ TYPE $ AMOUNT STATE $;
RUN;

/* EXAMPLE 13 */
DATA SAHU.CLINIHUNT_SYSTEM;
INFILE "/home/u64536648/AI GURU/CLINIH.txt" FIRSTOBS=3;
INPUT ID BRANCH $ MARKS RESULT $;
RUN;

/* EXAMPLE 14 */
DATA SAHU. EMPOYEE_LIST;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" FIRSTOBS=2;
INPUT EPLPYEE_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 15 */
DATA SAHU.FLIGHT_LIST;
INFILE "/home/u64536648/AI GURU/flights.txt" FIRSTOBS=4;
INPUT FLIGHT_ID $ COMPANY $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 16  */
DATA SAHU.HOSPITALS_LIST;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" FIRSTOBS=4;
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 17 */
DATA SAHU.LIBRARY_LIST;
INFILE "/home/u64536648/AI GURU/library.txt" FIRSTOBS=2;
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;

/* EXAMPLE 18 */
DATA SAHU.MOVIES_LIST;
INFILE "/home/u64536648/AI GURU/movies.txt" FIRSTOBS=2;
INPUT MOVIE_ID $ TITLE $ TYPE $ YEAR RATING;
RUN;

/* EXAMPLE 19 */
DATA SAHU.PATIENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/patients.txt" FIRSTOBS=5;
INPUT PATIENT_ID $ NAME $ AGE DISEASE $ WARD $;
RUN;

/* EXAMPLE 20 */
DATA SAHU.PRODUCTS_RECORD;
INFILE "/home/u64536648/AI GURU/products.txt" FIRSTOBS=3;
INPUT PRODUCT_ID $ PRODUCT $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 21  */
DATA SAHU.SALES_RECORD;
INFILE "/home/u64536648/AI GURU/sales.txt" FIRSTOBS=2;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 22 */
DATA SAHU.STUDENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/students.txt" FIRSTOBS=2;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 23 */
DATA SAHU.SALES_XYZ;
INFILE "/home/u64536648/AI GURU/sales.txt" FIRSTOBS=2;
INPUT ORDER_ID $ ITEM $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 24 */
DATA SAHU.STUDENT_XYZ;
INFILE "/home/u64536648/AI GURU/students.txt" FIRSTOBS=3;
INPUT STUDENT_ID $ NAME $  STREAM $ YEAR CGPA;
RUN;

/* EXAMPLE 25 */
DATA SAHU.HOSPITAL_XYZ;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" FIRSTOBS=4;
INPUT HOSPITAL_ID $ HOSPITAL_NAME $ LOCATION $ CAPACITY RATINGS;
RUN;
 
/* EXAMPLE 26 */
DATA SAHU.FLIGHTS_XYZ;
INFILE "/home/u64536648/AI GURU/flights.txt" FIRSTOBS=2;
INPUT FLIGHT_ID $ AIRLINE $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 27 */
DATA SAHU.PRODUCTS_XYZ;
INFILE "/home/u64536648/AI GURU/products.txt" FIRSTOBS=3;
INPUT PRODUCT_ID $ NAME $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 28 */
DATA SAHU.LIBRARY_XYZ;
INFILE "/home/u64536648/AI GURU/library.txt" FIRSTOBS=2;
INPUT BOOK_ID $ NAME $ TYPE $ AVAILABLITY $ RACK $;
RUN;

/* EXAMPLE 29 */
DATA SAHU.BANK_XYZ;
INFILE "/home/u64536648/AI GURU/bank.txt" FIRSTOBS=3;
INPUT ACCOUNT_ID $ NAME $ TYPE $ BALANCE LOCATION $;
RUN;

/* EXAMPLE 30 */
DATA SAHU.EMPLOYEE_XYZ;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" FIRSTOBS=3;
INPUT EMP_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 31 */
DATA SAHU.CLINIHUT_XYZ;
INFILE "/home/u64536648/AI GURU/CLINIH.txt" FIRSTOBS=2;
INPUT ID BRANCH $ STUDENT REMARKS $;
RUN;

/* EXAMPLE 32 */
DATA SAHU.BANK_Z;
INFILE "/home/u64536648/AI GURU/bank.txt" FIRSTOBS=3;
INPUT ACCOUNT_ID $ NAME $ TYPE $ BALANCE LOCATION $;
RUN;

/* EXAMPLE 33 */
DATA SAHU.EMPLOYEE_Z;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" FIRSTOBS=3;
INPUT EMP_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 34 */
DATA SAHU.FLIGHTS_Z;
INFILE "/home/u64536648/AI GURU/flights.txt" FIRSTOBS=2;
INPUT FLIGHT_ID $ AIRLINE $ TO $ FROM $ PRICE;
RUN;

/* EXAMPLE 35 */
DATA SAHU.SALES_Z;
INFILE "/home/u64536648/AI GURU/sales.txt" FIRSTOBS=3;
INPUT ORDER_ID $ ITEM $ QTY PRICE REGION $;
RUN; 

/* EXAMPLE 36 */
DATA SAHU.STUDENT_Z;
INFILE "/home/u64536648/AI GURU/students.txt" FIRSTOBS=2;
INPUT STUDENT_ID $ NAME $  STREAM $ YEAR CGPA;
RUN;

/* EXAMPLE 37 */
DATA SAHU.HOSPITAL_Z;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" FIRSTOBS=2;
INPUT HOSPITAL_ID $ HOSPITAL_NAME $ LOCATION $ CAPACITY RATINGS;
RUN;
 
/* EXAMPLE 38 */
DATA SAHU.FLIGHTS_XYZ;
INFILE "/home/u64536648/AI GURU/flights.txt" FIRSTOBS=3;
INPUT FLIGHT_ID $ AIRLINE $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 39  */
DATA SAHU.HOSPITALS_Z;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" FIRSTOBS=3;
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 40 */
DATA SAHU.LIBRARY_Z;
INFILE "/home/u64536648/AI GURU/library.txt" FIRSTOBS=3;
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;


/* 40 EXAMPLE OF OBS */

/* EXAMPLE 1 */
DATA SAHU.BANK_STATMENTS;
INFILE "/home/u64536648/AI GURU/bank.txt" OBS=3;
INPUT ACCOUYNT_ID $ NAME $ TYPE $ AMOUNT STATE $;
RUN;

/* EXAMPLE 2 */
DATA SAHU.CLINIHUNT_FILE;
INFILE "/home/u64536648/AI GURU/CLINIH.txt" OBS=2;
INPUT ID BRANCH $ MARKS RESULT $;
RUN;

/* EXAMPLE 3 */
DATA SAHU. EMPOYEE_RECORDINGS;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" OBS=4;
INPUT EPLPYEE_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 4 */
DATA SAHU.FLIGHT_PRICES;
INFILE "/home/u64536648/AI GURU/flights.txt" OBS=3;
INPUT FLIGHT_ID $ COMPANY $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 5  */
DATA SAHU.HOSPITALS_RECORDS;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" OBS=2;
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 6 */
DATA SAHU.LIBRARY_RECORDS;
INFILE "/home/u64536648/AI GURU/library.txt" OBS=4;
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;

/* EXAMPLE 7 */
DATA SAHU.MOVIES_ROOM;
INFILE "/home/u64536648/AI GURU/movies.txt" OBS=3;
INPUT MOVIE_ID $ TITLE $ TYPE $ YEAR RATING;
RUN;

/* EXAMPLE 8 */
DATA SAHU.PATIENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/patients.txt" OBS=5;
INPUT PATIENT_ID $ NAME $ AGE DISEASE $ WARD $;
RUN;

/* EXAMPLE 9 */
DATA SAHU.PRODUCTS_RECORD;
INFILE "/home/u64536648/AI GURU/products.txt" OBS=4;
INPUT PRODUCT_ID $ PRODUCT $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 10  */
DATA SAHU.SALES_RECORD;
INFILE "/home/u64536648/AI GURU/sales.txt" OBS=2;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 11 */
DATA SAHU.STUDENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/students.txt" OBS=3;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 12 */
DATA SAHU.BANK_CROUP;
INFILE "/home/u64536648/AI GURU/bank.txt" OBS=2;
INPUT ACCOUYNT_ID $ NAME $ TYPE $ AMOUNT STATE $;
RUN;

/* EXAMPLE 13 */
DATA SAHU.CLINIHUNT_SYSTEM;
INFILE "/home/u64536648/AI GURU/CLINIH.txt" OBS=3;
INPUT ID BRANCH $ MARKS RESULT $;
RUN;

/* EXAMPLE 14 */
DATA SAHU. EMPOYEE_LIST;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" OBS=2;
INPUT EPLPYEE_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 15 */
DATA SAHU.FLIGHT_LIST;
INFILE "/home/u64536648/AI GURU/flights.txt" OBS=4;
INPUT FLIGHT_ID $ COMPANY $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 16  */
DATA SAHU.HOSPITALS_LIST;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" OBS=4;
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 17 */
DATA SAHU.LIBRARY_LIST;
INFILE "/home/u64536648/AI GURU/library.txt" OBS=2;
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;

/* EXAMPLE 18 */
DATA SAHU.MOVIES_LIST;
INFILE "/home/u64536648/AI GURU/movies.txt" OBS=2;
INPUT MOVIE_ID $ TITLE $ TYPE $ YEAR RATING;
RUN;

/* EXAMPLE 19 */
DATA SAHU.PATIENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/patients.txt" OBS=5;
INPUT PATIENT_ID $ NAME $ AGE DISEASE $ WARD $;
RUN;

/* EXAMPLE 20 */
DATA SAHU.PRODUCTS_RECORD;
INFILE "/home/u64536648/AI GURU/products.txt" OBS=3;
INPUT PRODUCT_ID $ PRODUCT $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 21  */
DATA SAHU.SALES_RECORD;
INFILE "/home/u64536648/AI GURU/sales.txt" OBS=2;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 22 */
DATA SAHU.STUDENTS_RECORDS;
INFILE "/home/u64536648/AI GURU/students.txt" OBS=2;
INPUT ORDER_ID $ ITEM_NAME $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 23 */
DATA SAHU.SALES_XYZ;
INFILE "/home/u64536648/AI GURU/sales.txt" OBS=2;
INPUT ORDER_ID $ ITEM $ QTY PRICE REGION $;
RUN;

/* EXAMPLE 24 */
DATA SAHU.STUDENT_XYZ;
INFILE "/home/u64536648/AI GURU/students.txt" OBS=3;
INPUT STUDENT_ID $ NAME $  STREAM $ YEAR CGPA;
RUN;

/* EXAMPLE 25 */
DATA SAHU.HOSPITAL_XYZ;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" OBS=4;
INPUT HOSPITAL_ID $ HOSPITAL_NAME $ LOCATION $ CAPACITY RATINGS;
RUN;
 
/* EXAMPLE 26 */
DATA SAHU.FLIGHTS_XYZ;
INFILE "/home/u64536648/AI GURU/flights.txt" OBS=2;
INPUT FLIGHT_ID $ AIRLINE $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 27 */
DATA SAHU.PRODUCTS_XYZ;
INFILE "/home/u64536648/AI GURU/products.txt" OBS=3;
INPUT PRODUCT_ID $ NAME $ TYPE $ PRICE STOCK;
RUN;

/* EXAMPLE 28 */
DATA SAHU.LIBRARY_XYZ;
INFILE "/home/u64536648/AI GURU/library.txt" OBS=2;
INPUT BOOK_ID $ NAME $ TYPE $ AVAILABLITY $ RACK $;
RUN;

/* EXAMPLE 29 */
DATA SAHU.BANK_XYZ;
INFILE "/home/u64536648/AI GURU/bank.txt" OBS=3;
INPUT ACCOUNT_ID $ NAME $ TYPE $ BALANCE LOCATION $;
RUN;

/* EXAMPLE 30 */
DATA SAHU.EMPLOYEE_XYZ;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" OBS=3;
INPUT EMP_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 31 */
DATA SAHU.CLINIHUT_XYZ;
INFILE "/home/u64536648/AI GURU/CLINIH.txt" OBS=2;
INPUT ID BRANCH $ STUDENT REMARKS $;
RUN;

/* EXAMPLE 32 */
DATA SAHU.BANK_Z;
INFILE "/home/u64536648/AI GURU/bank.txt" OBS=3;
INPUT ACCOUNT_ID $ NAME $ TYPE $ BALANCE LOCATION $;
RUN;

/* EXAMPLE 33 */
DATA SAHU.EMPLOYEE_Z;
INFILE "/home/u64536648/AI GURU/employee_space_delimited.txt" OBS=3;
INPUT EMP_ID $ NAME $ DEPARTMENT $ SALARY;
RUN;

/* EXAMPLE 34 */
DATA SAHU.FLIGHTS_Z;
INFILE "/home/u64536648/AI GURU/flights.txt" OBS=2;
INPUT FLIGHT_ID $ AIRLINE $ TO $ FROM $ PRICE;
RUN;

/* EXAMPLE 35 */
DATA SAHU.SALES_Z;
INFILE "/home/u64536648/AI GURU/sales.txt" OBS=3;
INPUT ORDER_ID $ ITEM $ QTY PRICE REGION $;
RUN; 

/* EXAMPLE 36 */
DATA SAHU.STUDENT_Z;
INFILE "/home/u64536648/AI GURU/students.txt" OBS=2;
INPUT STUDENT_ID $ NAME $  STREAM $ YEAR CGPA;
RUN;

/* EXAMPLE 37 */
DATA SAHU.HOSPITAL_Z;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" OBS=2;
INPUT HOSPITAL_ID $ HOSPITAL_NAME $ LOCATION $ CAPACITY RATINGS;
RUN;
 
/* EXAMPLE 38 */
DATA SAHU.FLIGHTS_XYZ;
INFILE "/home/u64536648/AI GURU/flights.txt" OBS=3;
INPUT FLIGHT_ID $ AIRLINE $ FROM $ TO $ PRICE;
RUN;

/* EXAMPLE 39  */
DATA SAHU.HOSPITALS_Z;
INFILE "/home/u64536648/AI GURU/hospitals (1).txt" OBS=3;
INPUT HOSPITAL_ID $ NAME $ CITY $ BEDS RATINGS;
RUN;

/* EXAMPLE 40 */
DATA SAHU.LIBRARY_Z;
INFILE "/home/u64536648/AI GURU/library.txt" OBS=3;
INPUT BOOK_ID $ TITLE $ TYPE$ AVAILABLITY $ SELF $;
RUN;


/* 40 EXAMPLES OF MISSOVER  */

/* EXAMPLE 1  */
DATA SAHU.ORDER_REPORT;
INFILE "/home/u64536648/AI GURU/orders_missover.txt" MISSOVER;
INPUT ORDER_ID $ NAME $ ITEM $ QTY PRICE;
RUN;

/* EXAMPLE 2  */
DATA SAHU.PHARMACY_REPORT;
INFILE "/home/u64536648/AI GURU/pharmacy_missover.txt" MISSOVER;
INPUT DRUD_ID $ DRUG_NAME $ BATCH_NO $ POWER $ EXPIRY;
RUN;

/* EXAMPLE 3  */
DATA SAHU.SPACE_MISSION;
INFILE "/home/u64536648/AI GURU/space_missions.txt" MISSOVER;
INPUT MISSION_ID $ MISSION_NAME $ LAUNCH_YEAR STATUS $;
RUN;

/* EXAMPLE 4 */
DATA SAHU.VOLCANO_REPORT;
INFILE "/home/u64536648/AI GURU/volcanoes.txt" MISSOVER;
INPUT VOLCANO_ID $ MOUNTAIN $ COUNTRY $ HEIGHT;
RUN;

/* EXAMPLE 5 */
DATA SAHU.WILDLIFE_REPORT;
INFILE "/home/u64536648/AI GURU/wildlife.txt" MISSOVER;
INPUT ID $ ANIMAL_NAME $ REGION $ TICKET_PRICE;
RUN;

/* EXAMPLE 6 */
DATA SAHU.MUSEUM;
INFILE "/home/u64536648/AI GURU/museums.txt" MISSOVER;
INPUT MUSEUM_ID $ NAME $ CITY $ VISITORS;
RUN;

/* EXAMPLE 7 */
DATA SAHU.SATALITE_RECORD;
INFILE "/home/u64536648/AI GURU/satellites.txt" MISSOVER;
INPUT SATALITE_ID $ NAME $ ORBIT $ LAUNCH_YEAR;
RUN;

/* EXAMPLE 8 */
DATA SAHU.OLYMPICS_RECORDS;
INFILE "/home/u64536648/AI GURU/olympics.txt" MISSOVER;
INPUT ATHLETE_ID $ NAME $ SPORTS $ MEDALS COUNTRY $;
RUN;

/* EXAMPLE 9 */
DATA SAHU.FOSSIL_RECORD;
INFILE "/home/u64536648/AI GURU/fossils.txt" MISSOVER;
INPUT FOSSIL_ID $ NAME $ YEAR REGION;
RUN;

/* EXAMPLE 10 */
DATA SAHU.POWER_PLANT_RECORD;
INFILE "/home/u64536648/AI GURU/powerplants.txt" MISSOVER;
INPUT POWER_PLANT_ID $ NAME $ RESOURCES TONS STATE $;
RUN;

/* EXAMPLE 11  */
DATA SAHU.ESPORTS_RECORD;
INFILE "/home/u64536648/AI GURU/esports.txt" MISSOVER;
INPUT TEAM_ID $ TEAM_NAME $ REWARD ROUND $;
RUN;

/* EXAMPLE 12 */
DATA SAHU.WRECK_RECORD;
INFILE "/home/u64536648/AI GURU/shipwrecks.txt" MISSOVER;
INPUT WRECK_ID $ SHIP $ OCEAN $ DEPTH_IN_M;
RUN;

/* EXAMPLE 13 */
DATA SAHU.WEATHER_RECORD;
INFILE "/home/u64536648/AI GURU/weather_stations.txt" MISSOVER;
INPUT STATION_ID $ CITY $ RAINFALL TEMP;
RUN;

/* EXAMPLE 14 */
DATA SAHU.MOBILE_REVENUE;
INFILE "/home/u64536648/AI GURU/mobile_stores.txt" MISSOVER;
INPUT MOBILE_ID $ STORE $ BRAND $ REVENUE;
RUN;

/* EXAMPLE 15 */
DATA SAHU.UNIVERSITY_RECORDS;
INFILE "/home/u64536648/AI GURU/universities.txt" MISSOVER;
INPUT UNIVERSITY_ID $ UNIVERSITY $ STATE $ SEAT;
RUN;

/* EXAMPLE 16 */
DATA SAHU.EVCARS_RECORD;
INFILE "/home/u64536648/AI GURU/electric_vehicles.txt" MISSOVER;
INPUT EV_ID $ MODEL $ RANGE PRICE;
RUN;

/* EXAMPLE 17 */
DATA SAHU.PODCAST_RECORD;
INFILE "/home/u64536648/AI GURU/podcasts.txt" MISSOVER;
INPUT PODCAST_ID $ TITLE $ CATEGORY $ TIME ;
RUN;

/* EXAMPLE 18 */
DATA SAHU.THEMEPARK;
INFILE "/home/u64536648/AI GURU/theme_parks.txt" MISSOVER;
INPUT THEMEPARK_ID $ NAME $ COUNTRY $ BUDGET;
RUN;

/* EXAMPLE 19 */
DATA SAHU.STARTUP_RECORDS;
INFILE "/home/u64536648/AI GURU/startups.txt" MISSOVER;
INPUT STARTUP_ID $ CATEGORY $ TYPE $ ALLOCATION;
RUN;

/* EXAMPLE 20 */
DATA SAHU.MUSIC_FESTIVLE_RECORDS;
INFILE "/home/u64536648/AI GURU/music_festivals.txt" MISSOVER;
INPUT FESTIVLE_ID $ FESTIVLE $ COUNTRY $ ATTENDENCE;
RUN;

/* EXAMPLE 21 */
DATA SAHU.LAB_RECORDS;
INFILE "/home/u64536648/AI GURU/robotics_labs.txt" MISSOVER;
INPUT LAB_ID $ NAME $ COUNTRY $ RECORDS;
RUN;

/* EXAMPLE 22 */
DATA SAHU.RENEWABLE_ENERGY_RECORDS;
INFILE "/home/u64536648/AI GURU/renewable_energy.txt" MISSOVER;
INPUT RESOURCE_ID $ CATEGORY $ TYPE $ REMAINING STATE $;
RUN;

/* EXAMPLE 23 */
DATA SAHU.BOOKS_RECORD;
INFILE "/home/u64536648/AI GURU/bookstores.txt" MISSOVER;
INPUT STORE_ID $ BOOK $ STATE $ SOLD;
RUN;

/* EXAMPLE 24 */
DATA SAHU.AIRPORT_RECORDS;
INFILE "/home/u64536648/AI GURU/airports.txt" MISSOVER;
INPUT AIRPORT_ID $ FLIGHT $ STATE $ DISTANCE;
RUN;

/* EXAMPLE 25 */
DATA SAHU.HOTEL_ROOM_RECORD;
INFILE "/home/u64536648/AI GURU/hotels.txt" MISSOVER;
INPUT HOTEL_ID $ NAME $ LOCATION $ ROOMS;
RUN;

/* EXAMPLE 26 */
DATA SAHU.RESTURANT_DETAILS;
INFILE "/home/u64536648/AI GURU/restaurants.txt" MISSOVER;
INPUT RESTURANT_ID $ PROPERTY $ CUISCINE $ RATINGS;
RUN;

/* EXAMPLE 27 */
DATA SAHU.MARKET_RECORD;
INFILE "/home/u64536648/AI GURU/supermarkets.txt" MISSOVER;
INPUT MARKET_ID $ MARKET_NAME $ LOCATION $ REVENUE;
RUN;

/* EXAMPLE 28  */
DATA SAHU.ORDER_REPORT;
INFILE "/home/u64536648/AI GURU/orders_missover.txt" MISSOVER;
INPUT ORDER_ID $ NAME $ ITEM $ QTY PRICE;
RUN;

/* EXAMPLE 29  */
DATA SAHU.PHARMACY_REPORT;
INFILE "/home/u64536648/AI GURU/pharmacy_missover.txt" MISSOVER;
INPUT DRUD_ID $ DRUG_NAME $ BATCH_NO $ POWER $ EXPIRY;
RUN;

/* EXAMPLE 30  */
DATA SAHU.SPACE_MISSION;
INFILE "/home/u64536648/AI GURU/space_missions.txt" MISSOVER;
INPUT MISSION_ID $ MISSION_NAME $ LAUNCH_YEAR STATUS $;
RUN;

/* EXAMPLE 31 */
DATA SAHU.VOLCANO_REPORT;
INFILE "/home/u64536648/AI GURU/volcanoes.txt" MISSOVER;
INPUT VOLCANO_ID $ MOUNTAIN $ COUNTRY $ HEIGHT;
RUN;

/* EXAMPLE 32 */
DATA SAHU.WILDLIFE_REPORT;
INFILE "/home/u64536648/AI GURU/wildlife.txt" MISSOVER;
INPUT ID $ ANIMAL_NAME $ REGION $ TICKET_PRICE;
RUN;

/* EXAMPLE 33 */
DATA SAHU.MUSEUM;
INFILE "/home/u64536648/AI GURU/museums.txt" MISSOVER;
INPUT MUSEUM_ID $ NAME $ CITY $ VISITORS;
RUN;

/* EXAMPLE 34 */
DATA SAHU.SATALITE_RECORD;
INFILE "/home/u64536648/AI GURU/satellites.txt" MISSOVER;
INPUT SATALITE_ID $ NAME $ ORBIT $ LAUNCH_YEAR;
RUN;

/* EXAMPLE 35 */
DATA SAHU.OLYMPICS_RECORDS;
INFILE "/home/u64536648/AI GURU/olympics.txt" MISSOVER;
INPUT ATHLETE_ID $ NAME $ SPORTS $ MEDALS COUNTRY $;
RUN;

/* EXAMPLE 36 */
DATA SAHU.FOSSIL_RECORD;
INFILE "/home/u64536648/AI GURU/fossils.txt" MISSOVER;
INPUT FOSSIL_ID $ NAME $ YEAR REGION;
RUN;

/* EXAMPLE 37 */
DATA SAHU.POWER_PLANT_RECORD;
INFILE "/home/u64536648/AI GURU/powerplants.txt" MISSOVER;
INPUT POWER_PLANT_ID $ NAME $ RESOURCES TONS STATE $;
RUN;

/* EXAMPLE 38 */
DATA SAHU.LAB_RECORDS;
INFILE "/home/u64536648/AI GURU/robotics_labs.txt" MISSOVER;
INPUT LAB_ID $ NAME $ COUNTRY $ RECORDS;
RUN;

/* EXAMPLE 39 */
DATA SAHU.RENEWABLE_ENERGY_RECORDS;
INFILE "/home/u64536648/AI GURU/renewable_energy.txt" MISSOVER;
INPUT RESOURCE_ID $ CATEGORY $ TYPE $ REMAINING STATE $;
RUN;

/* EXAMPLE 40 */
DATA SAHU.BOOKS_RECORD;
INFILE "/home/u64536648/AI GURU/bookstores.txt" MISSOVER;
INPUT STORE_ID $ BOOK $ STATE $ SOLD;
RUN;

/* EXAMPLE 41 */
DATA SAHU.AIRPORT_RECORDS;
INFILE "/home/u64536648/AI GURU/airports.txt" MISSOVER;
INPUT AIRPORT_ID $ FLIGHT $ STATE $ DISTANCE;
RUN;

/* EXAMPLE 42 */
DATA SAHU.MARKET_ANALYSIS;
INFILE "/home/u64536648/AI GURU/supermarkets missover.txt" MISSOVER;
INPUT MARKET_ID $ NAME $ STATE $ REVENUE;
RUN;

/* EXAMPLE 43 */
DATA SAHU.RESTURANT_DETAILS;
INFILE "/home/u64536648/AI GURU/restaurants MIS.txt" MISSOVER;
INPUT RESTURANT_ID $ NAME $ CUISINE $ RATINGS;
RUN;















