
/* Access and Create Data Structures: 20-25% */

/* Create temporary and permanent SAS data sets */

/* Question 1  */

DATA WORK.TEENCLASS;
SET SASHELP.CLASS;

IF AGE >13 ;
DROP WEIGHT;
RUN;

/* QUESTION 2 */

LIBNAME MYDATA "C:\SAS\CertData" ;

PROC CONTENTS DATA=MYDATA._ALL_ NODS;
RUN;

/* QUESTION 3 */

PROC IMPORT DATAFILE="C:\SAS\CertData\class.xlsx"
OUT=WORK.CLASSXLS
DBMS=XLSX
REPLACE;
RUN;

/* QUESTION 4 */

DATA WORK.ALLSTUDENTS;
SET WORK.FALLCLASS WORK.SPRINGCLASS;
RUN;

/* QUESTION 5 */
PROC SORT DATA=WORK.DEMO OUT=SORTED1;
BY ID ; 
RUN;

PROC SORT DATA=WORK.SCORES OUT=SORTED2;
BY ID ;
RUN;


DATA WORK.COMBINED;
MERGE SORTED1 SORTED2;
BY ID ;
RUN;

/* QUESTION 6 */
DATA WORK.ORDERS_CUST;
MERGE WORK.CUSTOMERS  WORK.ORDERS ;
BY CUSTOMERID;
RUN;

/* QUESTION 7 */
DATA WORK.NEWHIRES;

LENGTH EMPLOYEE $20;
EMPLOYEE="JONES";
START_DATE=MDY(03,12,2018);

FORMAT START_DATE DATE9.;
RUN;

/* QUESTION 8 */

DATA WORK.EVENTS;
INFORMAT EVENTDATE DATE9. EVENTNAME $15.;
FORMAT EVENTDATE DATE9.;

INPUT EVENTDATE EVENTNAME;
CARDS;
15JAN2019 Meeting
03MAR2020 Conference
;
RUN;

/* QUESTION 9 */

LIBNAME XL XLSX "C:\SAS\CertData\sales.xlsx";

DATA WORK.Q1SALES;
SET XL.Q1;

RUN;

/* QUESTION 10 */
PROC IMPORT DATAFILE="C:\SAS\CertData\products.txt"
OUT=WORK.PRODUCTS
DBMS=DLM
REPLACE;
DELIMITER="09"X;
GUESSINGROWS=1000;
RUN;

/* QUESTION 11 */
DATA WORK.TALLMALES(KEEP=NAME AGE HEIGHT);
SET SASHELP.CLASS;

WHERE SEX="M" AND HEIGHT >65 ;
RUN;

/* QUESTION 12 */

DATA MYDATA.ADULTS;
SET SASHELP.CLASS;

IF AGE >=15;
DROP HEIGHT;

RUN;

/* QUESTION 13 */
DATA WORK.YOUNG;
SET SASHELP.CLASS(DROP=WEIGHT);

IF AGE <14;

KEEP NAME SEX AGE;
RUN;

/* QUESTION 14 */
PROC CONTENTS DATA=SASHELP.CLASS VARNUM;
RUN;

/* QUESTION 15 */
LIBNAME EMPXL XLSX "C:\SAS\Exam\staff.xlsx";

DATA WORK.RECENTHIRES;
SET EMPXL.EMPLOYEE(DROP=BONUS COMMISSION);
WHERE STARTDATE >="15MAY2017"D;

KEEP EMPNAME DEPT STARTDATE;
FORMAT STARTDATE MMDDYY10.;

RUN;


/* QUESTION 16 */
DATA MYLIB.ALLEMPS(KEEP=EMPID DEPT SALARY HIREDATE);
SET WORK.EMP2017 WORK.EMP2018;

WHERE HIREDATE >="01JAN2018"D;

DROP SALARY;
FORMAT HIREDATE DATE9.;
RUN;
